# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Master Build

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check-out
        uses: actions/checkout@v2
        if: success()

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build framework with Maven
        run: |
          mvn clean install

      - name: Execute test case
        run: |
          mvn test -Dgroups=androidCases